Found the names of the input and output tensors, now fixing args
Current runtime err:

```
2019-09-23 01:00:01.189765: W
tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at
transpose_op.cc:157 : Invalid argument: transpose expects a vector of
size 1. But input(1) is a vector of size 3
thread 'main' panicked at 'Run success: {inner:0x5589ea8b3860,
InvalidArgument: transpose expects a vector of size 1. But input(1) is a
vector of size 3
```

Getting there...!